#!/usr/bin/env bash

# Provides relevant context for LLM CLI tools, mainly with Aider.

# Get the current task description and notes
task=$(curtask)

# Echo the current task description
echo -e '# Current Task\n````markdown'
echo "$task"
echo -e '````'

# Loop over all matched Org IDs linked in the task ([[id:<ID>]]) and get their content
while read -r org_id; do
    if [[ -n "$org_id" ]]; then
        echo -e "# \`getorgnode $org_id\`\n\`\`\`\`markdown"
        getorgnode "$org_id"
        echo -e '````'
    fi
done < <(echo "$task" | grep -oP '\]\(id:([^\]]+)\)' | sed -r 's/.*id:([^\)]*).*/\1/')

# Get the last Git commit messages, from last 3 days
# Format: "## <commit-hash> (<author>, <time>)\n<subject>\n\n<body>"
echo -e '# Recent Git Commits (last 3 days)\n```markdown'
git log --since="3 days ago" --pretty=format:"## %h (%an, %ar)%n%s%n%n%b" | cat
echo -e '```'
