#!/bin/bash

orgMode="$(emacsclient --eval \
"(if (and (boundp 'org-clock-marker) org-clock-marker)
  (org-with-point-at org-clock-marker
    (let ((str (buffer-substring-no-properties
                (progn (org-back-to-heading t) (point))
                (progn (org-end-of-subtree t t) (point)))))
      (princ str)))
  (princ \"No active clock.\"))" | sed -e 's/^"//' -e 's/"$//')"

echo -en "$orgMode" |
  sed -zE 's/\nCLOCK: [^\n]+//g' |
  sed -zE 's/- (Note taken on [^\n]+|State [^\n]+)\\\\\n[ ]{2}/- /g'
