#!/bin/bash

# curtask - A script to display the Org clocked task from Emacs in the stdout

# Check if Emacs Daemon is running
if ! pgrep -x "emacs" > /dev/null; then
  echo "Emacs daemon is not running. Please start it first."
  exit 1
fi

orgMode="$(emacsclient --eval \
"(if (and (boundp 'org-clock-marker) org-clock-marker)
  (org-with-point-at org-clock-marker
    (let ((str (buffer-substring-no-properties
                (progn (org-back-to-heading t) (point))
                (progn (org-end-of-subtree t t) (point)))))
      (princ str)))
  (princ \"No active clock.\"))" | sed -e 's/^"//' -e 's/"$//')"

echo -en "$orgMode" |
  sed -zE 's/\nCLOCK: [^\n]+//g' |
  sed -zE 's/- (Note taken on [^\n]+|State [^\n]+)\\\\\n[ ]{2}/- /g'
