#!/usr/bin/env bash

dir="$1"


qnt() {
  if ! test -d "$dir"; then
    echo 0
    return
  fi

  ls $dir | wc -l
}

old=`qnt`

while true; do
  new=`qnt`
  fps=`echo -e "${new} - ${old}" | bc`
  echo "$fps files per second ($new)"
  sleep 1
  old=$new
done
