#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: $0 ORG_ID"
  exit 1
fi

org_id="$1"

elisp="
(let ((node (org-roam-node-from-id \"$org_id\")))
  (if node
      (expand-file-name (org-roam-node-file node))
    (princ \"ID not found\")))
"

emacsclient --eval "$elisp" | sed -e 's/^"//' -e 's/"$//'
