#!/usr/bin/env bash

# Sets the branch of the git repo to the hostname
# Useful to prevent commiting in wrong branches on
# repos as asciicasts, repot, etc...

# Check if the directory is a git repository
if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  echo "This script should be run inside a git repository."
  exit 1
fi

branch="$HOSTNAME"

# If is Qubes, add a prefix
if uname -r | grep 'qubes' &>/dev/null; then
  branch="qube-$branch"
fi

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ -z "$current_branch" ]; then
  echo "Error: Unable to determine the current branch."
  exit 1
fi

# If not different than current branch, exit
if [[ "$current_branch" == "$branch" ]]; then
  echo "Already on the branch"
  exit 0
fi

git checkout -b "$branch"

echo "Changed the branch from '$current_branch' to '$branch'"
