#!/usr/bin/env bash

# git-gc - Convenience script for `git gc` with a size comparison from before and after the GC.

# Check if running from the root of a git repository
if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  echo "This script must be run from the root of a git repository."
  exit 1
fi

originalSize="$(du -sh .git | awk '{printf "%s", $1}')"

time git gc $@

gcedSize="$(du -sh .git | awk '{print $1}')"

echo -e "\n$originalSize -> $gcedSize"
