#!/usr/bin/env bash

# Script that waits RET to record a session on a specific command,
# execute an post script and loops it again

command="$1"
postCommand="$2"
if [[ ! -n "$command" ]] || [[ ! -n "$postCommand" ]]; then
  echo "Usage: recloop COMMAND POST_COMMAND"
  exit 1
fi

timestampsFile="timestamps.jsonl"

while true; do
  echo "Press RET to start"
  read wait

  startEpoch="$(date '+%s')"
  castFile="$startEpoch.cast"

  # Add the marker and the terminal size to cast file
  lastSec=$(cat "$castFile" | tail -n1 | jq -r '.[0]')
  jq -nc --arg marker "$(date '+%H:%M:%S')" \
    '['$lastSec', "m", $marker]' \
    >>"$castFile"
  jq -nc --arg size "$(tput cols)x$(tput lines)" \
    '['$lastSec', "r", $size]' \
    >>"$castFile"

  # Start asciinema recording
  asciinema rec "$castFile" -c "$command" --stdin

  # Post
  echo "Executing post command"
  bash -c "$postCommand"

  endEpoch="$(date '+%s')"

  # Save session state to file
  jq -nc --arg start "$startEpoch" --arg end "$endEpoch" \
    '{start: $start, end: $end }' >>"$timestampsFile"

  # Commit
  git add "$castFile" "$timestampsFile"
  git commit -m 'chore(tracks): add session'

  # Delete the cast file to clean up
  rm "$castFile"

  echo "Done"
done
